workspace = { members = ["macros"] }
[package]
name = "kyuudb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0.7"
slab = "0.4.9"
vec_map = "0.8.2"
thiserror = "1.0.57"